### ISSUE TITLE
Changing Color

### ISSUE THREAD

**Issue by henrik-d** [cotag/orbicular#27]
Hey,
thanks for the great project. It would be cool, if one could change the color of the bar at runtime :)

**Comment by stakach** [comment]
You can with CSS and classes. Have to look at the resulting element and the elements you want to modify, shouldn't be too difficult

``` scss
@import "../../bower_components/orbicular/orbicular.scss";
@include orbicular();
orbicular.changeColor {
  div.co-fill {
    background-color: blue;
  }
}
```

Now you can add / remove the change color class using JS.
